### PR TITLE
Icbars

### PR DESCRIPTION
**Pull request by pnrobinson**

### CODE REVIEW

**Comment by ielis** [comment]
Looks good, I'll work on adding the newest version into Squirls cli

**Comment by pnrobinson** [comment]
@ielis  HTML5 has the new fieldset element (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/fieldset) that would be good -- if you can get the wiltype and vairant bits then we could put them in the title of the SVG (legend). I think that would look the best, but we can experiment

**Comment by ielis** [comment]
I'm not sure I am getting this. Should we create a `<form>` element in the report and use the controls to toggle SVG/barchart etc?

**Comment by pnrobinson** [comment]
let's talk later on!

**Pull request merged**
